swagger: '2.0'
info:
  description: 
    "Choice WebApp API for creating, commenting, and deciding on a choice and its alternatives"
  version: 1.1.0
  title: ChoiceAPI
  contact:
    name: CS3733 Team TeX
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
# basePath: /v2

paths:

  /loginUser/{choiceId}/{username}/{password}:
    post:
      operationId: loginUser
      description: "Check if user exists. If not, create new member, then login to choice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: choiceId
        type: string
        required: true
      - in: path
        name: username
        type: string
        required: true
      - in: path
        name: password
        type: string
        required: true
      responses:
        200:
          description: "member logged in successfully"
          schema:
            $ref: '#/definitions/Member'
        400:
          description: "loginUser : unexpected error"
      
  # Login but without password
  /loginUser/{choiceId}/{username}:
    post:
      operationId: loginUserWithoutPass
      description: "Check if user exists. If not, create new member, then login to choice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: choiceId
        type: string
        required: true
      - in: path
        name: username
        type: string
        required: true
      responses:
        200:
          description: "member logged in successfully"
          schema:
            $ref: '#/definitions/Member'
        400:
          description: "loginUser : unexpected error"


  /createModel:
    post:
      tags:
      - Model
      operationId: createModel
      description: "Create a model"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "model created successfully"
        400: 
          description: "createModel : unexpected error"
  /setTeam:
    post: 
      tags:
      - Model
      operationId: setTeam
      description: "Set team for model"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: team
        schema:
          $ref: '#/definitions/Team'
      responses:
        200:
          description: "operation successful"
        400: 
          description: "unexpected error"
  /setAdmin:
    post:
      tags:
      - Model
      operationId: setAdmin
      description: "Set admin of model"
      consumes:
      - "application/jason"
      produces: 
      - "application/json"
      parameters:
      - in: body
        name: adminUser
        schema:
          $ref: '#/definitions/Member'
      responses:
        200:
          description: "operation successful"
        400:
          description: "unexpected error"
        404: 
          description: "member not found or does not exist"

# Should be called using the given user to confirm he/she is admin
  /getReports:
    post:
      tags:
      - Model
      operationId: getReports
      description: "Return reports of all choices to admin user"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "operation successful"
          schema:
            type: array
            items: 
              $ref: '#/definitions/Report'
        400: 
          description: "unexpected error retriving reports"
        401: 
          description: "member not authorized"
        404:
          description: "no choices found to report"

  /getChoice/{choiceID}:
    get:
      tags:
      - Model
      operationId: getChoice
      description: "Return Choice"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: choiceID
        type: integer
        required: true
      responses:
        200:
          description: "operation successful"
        400: 
          description: "unexpected error retriving choice"
        
# Choice can only be deleted if it is over N days old
  /deleteOldChoice/{choiceId}:
    post:
      tags:
      - Model
      description: "Delete a given choice"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: choiceId
        type: integer
        required: true
      responses:
        200:
          description: "operation successful"
        400:
          description: "unexpected error"
        401:
          description: "choice is not old enough"
        404:
          description: "choice not found"

  /createTeam:
  # Team must be created with first member
    post:
      tags: 
      - Team
      operationId: createTeam
      description: "Create new team"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "team created"
          schema:
            $ref: '#/definitions/Team'
        400: 
          description: "createTeam : unexpected error"

  /addMember:
    post:
      tags:
      - Team
      operationId: addMember
      description: "Add new member to team"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: newMember
        schema: 
          $ref: '#/definitions/Member'
      responses:
        200:
          description: "member added to team"
          schema:
            $ref: '#/definitions/Team'
        400: 
          description: "addMember : unexpected error"

  /getMemberByName/{username}:
    get: 
      tags: 
      - Team
      operationId: getMemberByName
      description: "Get a member from the username"
      consumes:
      - "application/jason"
      produces: 
      - "application/json"
      parameters: 
      - in: path
        name: username
        type: string
        required: true
      responses:
        200: 
          description: "member retrieved successfully"
          schema:
            $ref: '#/definitions/Member'
        400: 
          description: "getMemberByName : unexpected error"
        404:
          description: "member not found"

  /createMember/{username}/{password}:
  # If no password, set as ""
    post:
      tags: 
      - Member
      operationId: createMemberWithPassword
      description: "Create a new member"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: username
        type: string
        required: true
      - in: path
        name: password
        type: string
        required: true
      responses:
        200:
          description: "member with password created successfully"
          schema:
            $ref: '#/definitions/Member'
        400: 
          description: "createMemberWithPassword : unexpected error"

  /createChoice/{choiceDesc}:
    post:
      tags: 
      - Choice
      operationId: createChoice
      description: "Create new choice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: choiceDesc
        type: string
        required: true
      responses:
        200:
          description: "new choice created successfully"
          schema:
            $ref: '#/definitions/Choice'
        400: 
          description: "createChoice : unexpected error"

  /addAlt/{aid}/{altDesc}:
    post:
      tags:
      - Choice
      operationId: addAlt
      description: "Add an alternative to a given choice"
      consumes: 
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: aid
        type: integer
        required: true
      - in: path
        name: altDesc
        type: string
        required: true
      - in: body
        name: givenChoice
        schema:
          $ref: '#/definitions/Choice'
      responses:
        200:
          description: "alternative added successfully"
          schema:
            $ref: '#/definitions/Choice'
        400:
          description: "addAlt : unexpected error"
      
  
  /completeChoice/{choiceId}:
    post:
      tags: 
      - Choice
      operationId: completeChoice
      description: "Complete a choice"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: choiceId
        type: integer
        required: true
      responses:
        200:
          description: "choice marked complete"
          schema:
            $ref: '#/definitions/Choice'
        400: 
          description: "completeChoice : unexpected error"

  /makeReport:
    post:
      tags:
      - Choice
      operationId: makeReport
      description: "Creates and returns a report of a choice"
      produces:
      - "application/json"
      parameters: 
      - in: body
        name: choice
        schema:
          $ref: '#/definitions/Choice'
      responses:
        200: 
          description: "report created successfully"
          schema: 
            $ref: '#/definitions/Report'
        400:
          description: "unexpected error"

  /createAlternative/{altNum}/{altDesc}:
    post:
      tags: 
      - Alternative
      operationId: createAlternative
      description: "Create new alternative"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: altNum
        type: string
        required: true
      - in: path
        name: altDesc
        type: string
        required: true
      responses:
        200:
          description: "alternative created successfully"
          schema:
            $ref: '#/definitions/Alternative'
        400: 
          description: "createAlternative : unexpected error"

  /addFeedback/{altId}/{description}:
    post:
      tags:
      - Alternative
      operationId: addFeedback
      description: "Add feedback to alternative"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: altId
        type: string
        required: true
      - in: path
        name: description
        type: string
        required: true
      - in: body
        name: feedback
        schema:
          $ref: '#/definitions/Feedback'
      responses:
        200:
          description: "feedback added successfully"
          schema:
            $ref: '#/definitions/Feedback'
        400: 
          description: "addFeedback : unexpected error"

  /addApprover:
    post:
      tags: 
      - Alternative
      operationId: addApprover
      description: "Add memeber name to Alternatives approver list"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      # Actual method will extract username from participating member
      - in: body
        name: addedMember
        schema: 
          $ref: '#/definitions/Member'
      responses:
        200:
          description: "approver added successfully"
          schema:
            $ref: '#/definitions/Alternative'
        400: 
          description: "addApprover : unexpected error"
 
  /addDisapprover:
    post:
      tags: 
      - Alternative
      operationId: addDisapprover
      description: "Add memeber name to Alternatives approver list"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      # Actual method will extract username from participating member
      - in: body
        name: addedMember
        schema: 
          $ref: '#/definitions/Member'
      responses:
        200:
          description: "disapprover added successfully"
          schema:
            $ref: '#/definitions/Alternative'
        400: 
          description: "addDisapprover : unexpected error"

  /removeApprover:
    post:
      tags: 
      - Alternative
      operationId: removeApprover
      description: "Remove member name from Alternatives approver list"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      # Actual method will extract username from participating member
      - in: body
        name: addedMember
        schema: 
          $ref: '#/definitions/Member'
      responses:
        200:
          description: "approver removed successfully"
          schema:
            $ref: '#/definitions/Alternative'
        400: 
          description: "Approver : unexpected error"
 
  /removeDisapprover:
    post:
      tags: 
      - Alternative
      operationId: removeDisapprover
      description: "Remove member name from Alternatives approver list"
      consumes:
      - "application/jason"
      produces:
      - "application/json"
      parameters:
      # Actual method will extract username from participating member
      - in: body
        name: addedMember
        schema: 
          $ref: '#/definitions/Member'
      responses:
        200:
          description: "disapprover removed successfully"
          schema:
            $ref: '#/definitions/Alternative'
        400: 
          description: "removeDisapprover : unexpected error"

  /createFeedback/{description}:
    post:
      tags:
      - Feedback
      operationId: createFeedback
      description: "Create new feedback"
      consumes:
      - "application/jason"
      parameters:
      # Actual method will extract username from participating member
      - in: body
        name: author
        schema:
          $ref: "#/definitions/Member"
      - in: path
        name: description
        type: string
        required: true
      responses:
        200:
          description: "feedback created successfully"
          schema:
            $ref: "#/definitions/Feedback"
        400: 
          description: "createFeedback : unexpected error"

# Report constructor, the main usage is in Choice class
  /createReport/{choiceId}:
    post:
      tags:
      - Report
      operationId: createReport
      description: "Report constructor"
      consumes:
      - "application/jason"
      produces: 
      - "application/json"
      parameters:
      - in: path
        name: choiceId
        type: integer
        required: true
      responses:
        200:
          description: "report created successfully"
          schema:
            $ref: '#/definitions/Report'
        400: 
          description: "createReport : unexpected error"
  
definitions:
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
  Report:
    type: object
    properties:
      choiceID:
        type: string
      completed:
        type: boolean
      dateOfCompletion:
        type: object
  Choice:
    type: object
    description: Provides alternatives to choice
    properties:
      id:
        type: integer
      description:
        type: string
      teamSize:
        type: integer
      alternatives:
        type: array
        items:
          $ref: '#/definitions/Alternative'
      dateOfCreation:
        type: object
      dateofCompleion:
        type: object
      finalChoice:
        type: integer
        format: int32
  Alternative:
    type: object
    description: Provides alternative to choice
    properties:
      aid:
        type: integer
      description: 
        type: string
      approvers: 
        type: array
        items:
          type: string
      disapprovers: 
        type: array
        items:
          type: string
      feedback: 
        type: array
        items:
          $ref: '#/definitions/Feedback'
  Member:
    type: object
    properties:
      name:
        type: string
      password:
        type: string
  Feedback:
    type: object
    properties:
      timestamp:
        type: integer
      description:
        type: string
      creator:
        type: string
  Team:
    type: object
    properties: 
      teamSize: 
        type: integer
      members: 
        type: array
        items:
          $ref: '#/definitions/Member'
      choice:
        $ref: '#/definitions/Choice'


externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /cs3733TeX/ChoiceAPI/1.0.0
schemes:
 - https
 - http